import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './tailwind.css';
import Providers from './providers';
import { Suspense } from 'react';
import Loading from './loading';
import { ProgressBar } from 'src/components/ProgressBar';

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <Providers>
            <main>{children}</main>
            <ProgressBar />
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
