import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { StyledProvider } from 'src/providers/styled.provider';
import { ThemeProvider } from 'src/providers/theme.provider';

import './globals.css';
import './tailwind.css';
import { AuthProvider } from 'src/providers/auth.provider';

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <main className="">
          <ThemeProvider>
            <StyledProvider>
              <AuthProvider>
                {children}
              </AuthProvider>
            </StyledProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
